# mezora theme - sauce for macchina cli

separator = "->"
separator_color = "red"
key_color = "red"
prefer_small_ascii = true
hide_ascii = true

[palette]
type = "Dark"
visible = true
glyph = " ⬤ "

[box]
title = " nyzs "
border = "double"
visible = true

[bar]
glyph = "▮ "
hide_delimiters = true
visible = true

[randomize]
key_color = false
separator_color = false

# [custom_ascii]
# color = "red"
# path = "C:/Users/OkanT/Desktop/dev/configs/ascii/arch.txt"


[keys]
host = "  host"
kernel = "k kernel"
distro = " distro"
packages = " packages"
terminal = " terminal"
shell = " shell"
cpu = " cpu"
cpu_load = " cpu"
memory = " memory"
battery = "󰁹 battery"
os = " os"
uptime = "󰄉 uptime"
